services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ai_responses
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/ai_responses
      - GROQ_API_KEY=${GROQ_API_KEY}
    depends_on:
      - db

  frontend:
    build: ./frontend
    command: streamlit run app.py
    volumes:
      - ./frontend:/app
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://backend:8000/api
    depends_on:
      - backend

volumes:
  postgres_data: